### ISSUE TITLE
Format doesn't work

### ISSUE THREAD

**Issue by afonso177** [alefragnani/vscode-delphi-keybindings#1]
Hi, I believe the Format instruction for Ctrl+D is wrongly set, it should be editor.action.formatdocument instead of editor.action.format.

**Comment by alefragnani** [comment]
Hi @afonso177,

You are right. It's set to the wrong command 👍 

If I  remember well, there was only one command (`Format`) available, but a while ago, it was divided in two (`Document` and `Selection`). I didn't remember to update the keybinding.

I will release an update soon

Thanks

**Comment by alefragnani** [comment]
Hi @afonso177 ,

Sorry for taking so long to fix this. Please, update and enjoy the keybindings.
