### ISSUE TITLE
[FYI] - Keyboard Macro support

### ISSUE THREAD

**Issue by tshino** [alefragnani/vscode-delphi-keybindings#48]
I'm afraid this is not an actual issue or feature request on your project but just for your information.
I created an extension for VS Code to realize keyboard macro recording.

- Keyboard Macro Beta - Visual Studio Marketplace
  https://marketplace.visualstudio.com/items?itemName=tshino.kb-macro

The extension allows users to record a keyboard input sequence and to playback it later.

And I found the information that the Delphi IDE has the same functionality.
I thought it would be nice if your Delphi Keymap could work together with my extension.
So I added Delphi Keymap support to my extension.

- Keymap Wrappers - tshino/vscode-kb-macro
  https://github.com/tshino/vscode-kb-macro/tree/main/keymap-wrapper

I think it could be an out-of-project contribution for your Delphi Keymap.

If you have time, I would like to ask you to try it and to have some random testing to confirm it works.

Thanks.

**Comment by tshino** [comment]
Okay, I think it works well.
I hope this information will help you and your extension's users.
Thanks.

**Comment by alefragnani** [comment]
Hi @tshino ,

First of all, I'm sorry for not answering you earlier.

Even tho, I'm glad to know you could confirm it does work. I don't use macros that much, but I understand it is a great feature for a bunch of users.

Thank you
