### ISSUE TITLE
[FEATURE] - Please create some instructions on how to build the extension.  

### ISSUE THREAD

**Issue by mvancanneyt** [alefragnani/vscode-delphi-keybindings#79]
I'm trying to get the extension installed in vscodium.  I can download the .vsix from VS code market place, but I would rather  build the extension myself in order to add some keybindings.

Naively calling npm run build does not work, I'm getting errors, from which I deduce that it tries to reference another repository. 

Here is the build log:

<pre>assets by status 7.05 KiB <font color="#26A269"><b>[cached]</b></font> 1 asset
modules by path <b>./src/</b> 12.5 KiB
  modules by path <b>./src/*.ts</b> 5 KiB
    <b>./src/extension.ts</b> 908 bytes <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
    <b>./src/container.ts</b> 636 bytes <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
    <b>./src/commands.ts</b> 2.21 KiB <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
    <b>./src/constants.ts</b> 537 bytes <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
    <b>./src/docWikiUriBuilder.ts</b> 769 bytes <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
  modules with errors 7.51 KiB <font color="#C01C28"><b>[errors]</b></font>
    <b>./src/whats-new/commands.ts</b> 1.24 KiB <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font> <font color="#C01C28"><b>[1 error]</b></font>
    <b>./src/whats-new/contentProvider.ts</b> 6.27 KiB <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font> <font color="#C01C28"><b>[1 error]</b></font>
<b>external &quot;vscode&quot;</b> 42 bytes <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
<b>./node_modules/vscode-ext-selection/lib/index.js</b> 3.49 KiB <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>

<font color="#C01C28"><b>ERROR</b></font> in <b>./src/whats-new/commands.ts</b> <font color="#26A269"><b>10:18-63</b></font>
<b>Module </b><font color="#C01C28"><b>not found</b></font><b>: </b><font color="#C01C28"><b>Error</b></font><b>: Can&apos;t resolve &apos;../../vscode-whats-new/src/Manager&apos; in &apos;/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new&apos;</b>
 @ ./src/extension.ts 8:19-50

<font color="#C01C28"><b>ERROR</b></font> in <b>./src/whats-new/contentProvider.ts</b> <font color="#26A269"><b>8:26-79</b></font>
<b>Module </b><font color="#C01C28"><b>not found</b></font><b>: </b><font color="#C01C28"><b>Error</b></font><b>: Can&apos;t resolve &apos;../../vscode-whats-new/src/ContentProvider&apos; in &apos;/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new&apos;</b>
 @ ./src/whats-new/commands.ts 11:26-54
 @ ./src/extension.ts 8:19-50

<font color="#C01C28"><b>ERROR</b></font> in <b>/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new/commands.ts</b>
<b>./src/whats-new/commands.ts</b> <font color="#26A269"><b>8:32-68</b></font>
<font color="#5E5C64">[tsl] </font><font color="#C01C28"><b>ERROR in </b></font><font color="#2AA1B3"><b>/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new/commands.ts(8,33)</b></font>
<font color="#C01C28"><b>      TS2307: Cannot find module &apos;../../vscode-whats-new/src/Manager&apos; or its corresponding type declarations.</b></font>
 @ ./src/extension.ts 8:19-50

<font color="#C01C28"><b>ERROR</b></font> in <b>/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new/contentProvider.ts</b>
<b>./src/whats-new/contentProvider.ts</b> <font color="#26A269"><b>6:125-169</b></font>
<font color="#5E5C64">[tsl] </font><font color="#C01C28"><b>ERROR in </b></font><font color="#2AA1B3"><b>/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new/contentProvider.ts(6,126)</b></font>
<font color="#C01C28"><b>      TS2307: Cannot find module &apos;../../vscode-whats-new/src/ContentProvider&apos; or its corresponding type declarations.</b></font>
 @ ./src/whats-new/commands.ts 11:26-54
 @ ./src/extension.ts 8:19-50

<font color="#A2734C"><b>4 errors have detailed information that is not shown.</b></font>
<font color="#A2734C"><b>Use &apos;stats.errorDetails: true&apos; resp. &apos;--stats-error-details&apos; to show it.</b></font>

webpack 5.76.0 compiled with <font color="#C01C28"><b>4 errors</b></font> in 1793 ms

assets by status 7.05 KiB <font color="#26A269"><b>[cached]</b></font> 1 asset
modules by path <b>./src/</b> 12.5 KiB
  modules by path <b>./src/*.ts</b> 5 KiB
    <b>./src/extension.ts</b> 908 bytes <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
    <b>./src/container.ts</b> 636 bytes <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
    <b>./src/commands.ts</b> 2.21 KiB <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
    <b>./src/constants.ts</b> 537 bytes <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
    <b>./src/docWikiUriBuilder.ts</b> 769 bytes <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
  modules with errors 7.51 KiB <font color="#C01C28"><b>[errors]</b></font>
    <b>./src/whats-new/commands.ts</b> 1.24 KiB <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font> <font color="#C01C28"><b>[1 error]</b></font>
    <b>./src/whats-new/contentProvider.ts</b> 6.27 KiB <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font> <font color="#C01C28"><b>[1 error]</b></font>
<b>external &quot;vscode&quot;</b> 42 bytes <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>
<b>./node_modules/vscode-ext-selection/lib/index.js</b> 3.49 KiB <font color="#A2734C"><b>[built]</b></font> <font color="#A2734C"><b>[code generated]</b></font>

<font color="#C01C28"><b>ERROR</b></font> in <b>./src/whats-new/commands.ts</b> <font color="#26A269"><b>10:18-63</b></font>
<b>Module </b><font color="#C01C28"><b>not found</b></font><b>: </b><font color="#C01C28"><b>Error</b></font><b>: Can&apos;t resolve &apos;../../vscode-whats-new/src/Manager&apos; in &apos;/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new&apos;</b>
 @ ./src/extension.ts 8:19-50

<font color="#C01C28"><b>ERROR</b></font> in <b>./src/whats-new/contentProvider.ts</b> <font color="#26A269"><b>8:26-79</b></font>
<b>Module </b><font color="#C01C28"><b>not found</b></font><b>: </b><font color="#C01C28"><b>Error</b></font><b>: Can&apos;t resolve &apos;../../vscode-whats-new/src/ContentProvider&apos; in &apos;/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new&apos;</b>
 @ ./src/whats-new/commands.ts 11:26-54
 @ ./src/extension.ts 8:19-50

<font color="#C01C28"><b>ERROR</b></font> in <b>/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new/commands.ts</b>
<b>./src/whats-new/commands.ts</b> <font color="#26A269"><b>8:32-68</b></font>
<font color="#5E5C64">[tsl] </font><font color="#C01C28"><b>ERROR in </b></font><font color="#2AA1B3"><b>/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new/commands.ts(8,33)</b></font>
<font color="#C01C28"><b>      TS2307: Cannot find module &apos;../../vscode-whats-new/src/Manager&apos; or its corresponding type declarations.</b></font>
 @ ./src/extension.ts 8:19-50

<font color="#C01C28"><b>ERROR</b></font> in <b>/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new/contentProvider.ts</b>
<b>./src/whats-new/contentProvider.ts</b> <font color="#26A269"><b>6:125-169</b></font>
<font color="#5E5C64">[tsl] </font><font color="#C01C28"><b>ERROR in </b></font><font color="#2AA1B3"><b>/home/michael/michael/Projects/vscode-delphi-keybindings/src/whats-new/contentProvider.ts(6,126)</b></font>
<font color="#C01C28"><b>      TS2307: Cannot find module &apos;../../vscode-whats-new/src/ContentProvider&apos; or its corresponding type declarations.</b></font>
 @ ./src/whats-new/commands.ts 11:26-54
 @ ./src/extension.ts 8:19-50

<font color="#A2734C"><b>4 errors have detailed information that is not shown.</b></font>
<font color="#A2734C"><b>Use &apos;stats.errorDetails: true&apos; resp. &apos;--stats-error-details&apos; to show it.</b></font>
</pre>

**Comment by alefragnani** [comment]
Hi @mvancanneyt ,

The instructions already exists, in the [CONTRIBUTING.md](https://github.com/alefragnani/vscode-delphi-keybindings/blob/master/CONTRIBUTING.md) file. You just have to follow the steps provided.

BTW, I have noticed a missing step in the `dependencies` section, but have already fixed so, you are good to go.

About VS Codium, I’m planning to release my extension on openvsx (#47 ), so it should officially available soon.

Hope this helps
